- name: Download Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /tools
    remote_src: yes

#- name: copy prometheus service file
#  ansible.builtin.template:


#- name: start prometheus service
#  ansible.builtin.systemd_service:
#    state: restarted
#    enabled: true
#    daemon_reload: true


